version: '3.3'

services: 
    app:
        build: .
        ports: 
            - 5000:5000


    db:
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "123"
        volumes:
            - "my_db:/var/lib/mysql"
            - "./init.sql:/docker-entrypoint-initdb.d/init.sql"

volumes:
    my_db: 
